baseURL = "https://jabyess.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "skelios"
publishDir = "docs"

[menu]

  [[menu.main]]
  identifier = "Home"
  name = "Home"
  title = "Home"
  url = "/"
  weight = -100

  [[menu.main]]
  identifier = "About"
  name = "About"
  title = "About"
  url = "/about/"
  weight = -90

  [[menu.main]]
  identifier = "Words"
  name = "Words"
  title = "Words"
  url = "/posts"
  weight = -80

  [[menu.main]]
  identifier = "Code"
  name = "Code"
  title = "Code"
  url = "https://github.com/jabyess/"
  weight = -70